# Generated by Django 5.2.16 on 2026-10-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='broker_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='case_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_broker',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='rto_agent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rto_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('permit', 'Permit'), ('fitness', 'Fitness'), ('puc', 'PUC'), ('tax', 'Tax'), ('fitness_puc', 'Fitness / PUC'), ('license', 'License'), ('broker', 'Broker'), ('transfer', 'Transfer'), ('hpt', 'HPT'), ('hpa', 'HPA'), ('odit', 'Audit'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_broker'], name='customers_c_is_brok_b2b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['broker_name'], name='customers_c_broker__6aa754_idx'),
        ),
    ]
